steps:
  # Membuat image dengan perintah "cloud build -t gcr.io/$PROJECT_ID/tcc-kelompok9-be ."
  # Project ID akan secara otomatis terisi ketika melakukan deploy di project yg dipilih
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-kelompok9-be", "."]

  # Meng-upload/push image yg telah dibuat ke Artifact Registry
  # Pada bagian ini, dijalankan perintah "docker push 'gcr.io/$PROJECT_ID/tcc-kelompok9-be'"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-kelompok9-be"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "tcc-kelompok9-be",
        "--image",
        "gcr.io/$PROJECT_ID/tcc-kelompok9-be",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME},PG_DB_HOST=${_PG_DB_HOST},PG_DB_NAME=${_PG_DB_NAME},PG_DB_PASSWORD=${_PG_DB_PASSWORD},PG_DB_USERNAME=${_PG_DB_USERNAME}",
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY
